#!/bin/bash

getinput findthebug > student/student_code.sh
cp ./buggy.sh ./student/buggy.sh


if grep -q -E "cd|ls|cat" ./student/student_code.sh; then
    feedback-result failed
    feedback-msg -em "Vous n'avez pas besoin d'utiliser la commande `cd`, `ls` ou `cat`"
fi

chmod +x ./student/buggy.sh
cd student
output=$(run_student sh ./student_code.sh)

if [[ -f "./args_err.txt" ]]; then
    feedback-result failed
    feedback-msg -em "Attention, le script buggy.sh prend comme argument un nombre entier"
    exit 0
fi

if [ "$output" = "42" ]; then
    feedback-result success
else
    feedback-result failed
    feedback-msg -em "Résultat de votre programme : $output"
fi