#!/bin/bash

getinput regex1 | tr -d '\r' > student/student_regex1
getinput regex2 | tr -d '\r' > student/student_regex2
getinput regex3 | tr -d '\r' > student/student_regex3
getinput regex4 | tr -d '\r' > student/student_regex4
getinput regex5 | tr -d '\r' > student/student_regex5
cp apache.log student/
cd student

regex1=$(cat student_regex1)
regex2=$(cat student_regex2)
regex3=$(cat student_regex3)
regex4=$(cat student_regex4)
regex5=$(cat student_regex5)

global_success=true

grep -oP "$regex1" apache.log > student_result1
grep -oP '.*0\d:\d{2}:\d{2}.*' apache.log > good_result1

if diff student_result1 good_result1; then
    feedback-result --id regex1 success
    feedback-msg -e -m "Correct" --id regex1
else
    feedback-result --id regex1 failed
    feedback-msg -e -m "Vous n'avez pas récupéré toutes requêtes faites strictement avant 10:00" --id regex1 
    global_success=false
fi

grep -oP "$regex2" apache.log > student_result2
grep -oP '.*\s-\s\w.*' apache.log > good_result2

if diff student_result2 good_result2; then
    feedback-result --id regex2 success
    feedback-msg -e -m "Correct" --id regex2
else
    feedback-result --id regex2 failed
    feedback-msg -e -m "Vous n'avez pas récupéré tous les requêtes où un userID est précisé" --id regex2
    global_success=false
fi

grep -oP "$regex3" apache.log > student_result3
grep -oP '.*"GET.*"\s2\d{2}.*' apache.log > good_result3

if diff student_result3 good_result3; then
    feedback-result --id regex3 success
    feedback-msg -e -m "Correct" --id regex3 
else
    feedback-result --id regex3 failed
    feedback-msg -e -m "Vous n'avez pas récupéré toutes les requêtes GET réussies" --id regex13
    global_success=false
fi

grep -oP "$regex4" apache.log > student_result4
grep -oP '.*"PUT.*HTTP\/2.0.*' apache.log > good_result4

if diff student_result4 good_result4; then
    feedback-result --id regex4 success
    feedback-msg -e -m "Correct" --id regex4 
else
    feedback-result --id regex4 failed
    feedback-msg -e -m "Vous n'avez pas récupéré toutes les requêtes PUT faites via HTTP 2.0" --id regex4 
    global_success=false
fi

grep -oP "$regex5" apache.log > student_result5
grep -oP '.*-\s\w.*:(0[1-9]|1[0-1]):\d{2}:\d{2}.*"GET.*".*\s[1-9][5-9]\d{2}$' apache.log > good_result5

if diff student_result5 good_result5; then
    feedback-result --id regex5 success
    feedback-msg -e -m "Correct" --id regex5
else
    feedback-result --id regex5 failed
    feedback-msg -e -m "Vous n'avez pas récupéré toutes les requêtes GET faites strictement avant 12:00 avec un nom d'utilisateur et avec une taille strictement supérieure à 1500" --id regex5
    global_success=false
fi

if [ $global_success = true ]; then
    feedback-result success
    feedback-msg -em "Bravo, vous avez réussi !"
else
    feedback-result failed
    feedback-msg -em "Vous avez quelques erreurs"
fi