#!/bin/bash

getinput regex1 | tr -d '\r' > student/student_regex1
getinput regex2 | tr -d '\r' > student/student_regex2
getinput regex3 | tr -d '\r' > student/student_regex3
getinput regex4 | tr -d '\r' > student/student_regex4
cp apache.log student/

regex1=$(cat student_regex1)
regex2=$(cat student_regex2)
regex3=$(cat student_regex3)
regex4=$(cat student_regex4)

cd student
output1=$(grep -oP $regex1 apache.log)
good_output1=$(grep -oP '(\d{1,3}\.){3}\d{1,3}' apache.log)

if [ $output1==$good_output1 ]; then
    feedback-result --id regex1 success
    feedback-msg -em "Bravo"
else
    feedback-result failed
    feedback-msg -em "Résultat de votre programme : $output1"
fi